config/routes.rb
Rails.application.routes.draw do

  resources :hsups
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :jourferies, :intemperies, :prestations, :machines, :clients, :employeurs
  resources :factures, :facture_lignes

  root 'prestations#calendrier'

  get '/calendrier', to: 'prestations#calendrier'
  get '/factures', to: 'prestations#facture'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  has_many :prestations
end

app/models/facture.rb
class Facture < ApplicationRecord
  belongs_to :employeur
  has_many :facture_lignes, dependent: :destroy
  has_many :prestations, through: :facture_lignes

  validates_presence_of :numero, :debut, :fin
  accepts_nested_attributes_for :facture_lignes

  def total
    self.remise = 0 unless self.remise
    total = 0
    self.prestations.each do |p|
      p.hsups.each do |hs|
        total = hs.qte * 35 + total
      end
    end
    total = total + facture_lignes.sum(:montant) - self.remise
  end

end

app/models/facture_ligne.rb
class FactureLigne < ApplicationRecord
  belongs_to :prestation
  belongs_to :facture

  # validates_presence_of :debut, :fin
end

app/models/hsup.rb
class Hsup < ApplicationRecord
  belongs_to :prestation
end

app/models/intemperie.rb
class Intemperie < ApplicationRecord
  def start_time
    self.date.to_datetime
  end
  def end_time
    self.date.to_datetime
  end
end

app/models/jourferie.rb
class Jourferie < ApplicationRecord
  def start_time
    self.date.to_datetime
  end
  def end_time
    self.date.to_datetime
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :employeur
  belongs_to :client
  belongs_to :machine
  has_many :hsups
  has_many :facture_lignes
  has_many :factures, through: :facture_lignes

  def start_time
    self.debut.to_datetime
  end
  def end_time
    self.fin.to_datetime
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/hsups_controller.rb
class HsupsController < ApplicationController
  before_action :set_hsup, only: [:show, :edit, :update, :destroy]
  before_action :get_today_prestations, :get_all_prestations, only: [:new, :edit]

  def index
    @hsups = Hsup.all
  end

  def show
  end

  def new
    @hsup = Hsup.new
  end

  def edit
  end

  def create
    @hsup = Hsup.new(hsup_params)

    respond_to do |format|
      if @hsup.save
        format.html { redirect_to hsups_url, notice: 'Hsup créée.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @hsup.update(hsup_params)
        format.html { redirect_to hsups_url, notice: 'Hsup mise à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @hsup.destroy
    respond_to do |format|
      format.html { redirect_to hsups_url, notice: 'Hsup détruite.' }
    end
  end

  private
    def set_hsup
      @hsup = Hsup.find(params[:id])
    end

    def hsup_params
      params.require(:hsup).permit(:qte, :date, :prestation_id)
    end

    def get_today_prestations
      @today_prestations = Prestation.where('debut <= ? AND fin >= ?', Date.today, Date.today)
    end

    def get_all_prestations
      @all_prestations = Prestation.all.order(fin: :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/hsups_helper.rb
module HsupsHelper
end

app/helpers/intemperies_helper.rb
module IntemperiesHelper
end

app/helpers/jourferies_helper.rb
module JourferiesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/prestations_helper.rb
module PrestationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MRGestion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="bg-light">
    <%= render "shared/navbar" %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>MR - Facture</title>
    <%= wicked_pdf_stylesheet_link_tag "application" -%>
    <%= javascript_include_tag "https://code.jquery.com/jquery-3.2.1.min.js" %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark sticky-top bg-dark">
  <a class="navbar-brand" href="<%= prestations_path %>"><span class="text-warning">MR</span>Gestion</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="dropdown-toggle btn btn-outline-warning" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= fa_icon('plus') %> Ajouter
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= new_prestation_path %>"><%= fa_icon('wrench') %> Prestation</a>
          <a class="dropdown-item" href="<%= new_facture_path %>"><%= fa_icon('file-pdf-o') %> Facture</a>
          <a class="dropdown-item" href="<%= new_employeur_path %>"><%= fa_icon('user') %> Employeur</a>
          <a class="dropdown-item" href="<%= new_client_path %>"><%= fa_icon('user-o') %> Client</a>
          <a class="dropdown-item" href="<%= new_machine_path %>"><%= fa_icon('truck') %> Machine</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= new_hsup_path %>"><%= fa_icon('clock-o') %> H sup'</a>
          <a class="dropdown-item" href="<%= new_intempery_path %>"><%= fa_icon('shower') %> Intempérie</a>
          <a class="dropdown-item" href="<%= new_jourfery_path %>"><%= fa_icon('hotel') %> Jour férié</a>
        </div>
      </li>
      <li class="nav-item <% if request.path.start_with?('/calendrier') %>active<% end %>">
        <a class="nav-link" href="/calendrier"><%= fa_icon('calendar', class: 'text-warning') %> Calendrier</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/factures') %>active<% end %>">
        <a class="nav-link" href="/factures"><%= fa_icon('file-pdf-o', class: 'text-warning') %> Factures</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/prestations') %>active<% end %>">
        <a class="nav-link" href="<%= prestations_path %>"><%= fa_icon('wrench', class: 'text-warning') %> Prestations</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/employeurs') %>active<% end %>">
        <a class="nav-link" href="<%= employeurs_path %>"><%= fa_icon('user', class: 'text-warning') %> Employeurs</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/clients') %>active<% end %>">
        <a class="nav-link" href="<%= clients_path %>"><%= fa_icon('user-o', class: 'text-warning') %> Clients</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/machines') %>active<% end %>">
        <a class="nav-link" href="<%= machines_path %>"><%= fa_icon('truck', class: 'text-warning') %> Machines</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/hsups') %>active<% end %>">
        <a class="nav-link" href="<%= hsups_path %>"><%= fa_icon('clock-o', class: 'text-warning') %> H sup'</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/intemperies') %>active<% end %>">
        <a class="nav-link" href="<%= intemperies_path %>"><%= fa_icon('shower', class: 'text-warning') %> Intempéries</a>
      </li>
      <li class="nav-item <% if request.path.start_with?('/jourferies') %>active<% end %>">
        <a class="nav-link" href="<%= jourferies_path %>"><%= fa_icon('hotel', class: 'text-warning') %> Jours fériés</a>
      </li>
    </ul>

    <ul class="navbar-nav my-2 my-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item  mr-2 mb-1">
          <%= link_to fa_icon("user-circle-o", class: "text-warning") + " " + 'Mon compte' , edit_user_registration_path, :class => 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to fa_icon("sign-out", class: "text-warning") + "Déconnexion", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>