config/routes.rb
Rails.application.routes.draw do

  resources :hsups
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :jourferies, :intemperies, :prestations, :machines, :clients, :employeurs
  resources :factures, :facture_lignes

  root 'prestations#calendrier'

  get '/calendrier', to: 'prestations#calendrier'
  get '/factures', to: 'prestations#facture'
end

app/models/hsup.rb
class Hsup < ApplicationRecord
  belongs_to :prestation
end

app/controllers/hsups_controller.rb
class HsupsController < ApplicationController
  before_action :set_hsup, only: [:show, :edit, :update, :destroy]
  before_action :get_today_prestations, :get_all_prestations, only: [:new, :edit]

  def index
    @hsups = Hsup.all
  end

  def show
  end

  def new
    @hsup = Hsup.new
  end

  def edit
  end

  def create
    @hsup = Hsup.new(hsup_params)

    respond_to do |format|
      if @hsup.save
        format.html { redirect_to hsups_url, notice: 'Hsup créée.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @hsup.update(hsup_params)
        format.html { redirect_to hsups_url, notice: 'Hsup mise à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @hsup.destroy
    respond_to do |format|
      format.html { redirect_to hsups_url, notice: 'Hsup détruite.' }
    end
  end

  private
    def set_hsup
      @hsup = Hsup.find(params[:id])
    end

    def hsup_params
      params.require(:hsup).permit(:qte, :date, :prestation_id)
    end

    def get_today_prestations
      @today_prestations = Prestation.where('debut <= ? AND fin >= ?', Date.today, Date.today)
    end

    def get_all_prestations
      @all_prestations = Prestation.all.order(fin: :desc)
    end
end

app/helpers/hsups_helper.rb
module HsupsHelper
end

app/views/hsups/_form.html.erb
<div class="container">

  <%= simple_form_for(@hsup) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <div class="row">
        <div class="col">
          <%= f.input :date, as: :string, input_html: {type: :date}, label: fa_icon('calendar')+' Date'  %>
        </div>
        <div class="col">
          <%= f.input :qte, label: 'Quantité, en heure' %>
        </div>
      </div>

      <h5>Sélectionner la prestation associée : </h5>

      <select id="hsup_prestation_id" class="form-control select required" name="hsup[prestation_id]">
        <% @today_prestations.each do |p| %>
          <option value="<%= p.id %>"><%= l(p.debut, format: '%d/%m/%y') %> - <%= l(p.fin, format: '%d/%m/%y') %> : <%= p.employeur.nom %>, <%= p.ville %></option>
        <% end %>

        <option value="" disabled="disabled">───────────────────────────────────</option>

        <% @all_prestations.each do |p| %>
          <option value="<%= p.id %>"><%= l(p.debut, format: '%d/%m/%y') %> - <%= l(p.fin, format: '%d/%m/%y') %> : <%= p.employeur.nom %>, <%= p.ville %></option>
        <% end %>
      </select>
      <p class="m-2 ">Début - Fin : Employeur, ville</p>

    </div>

    <div class="form-actions">
      <%= f.button :submit, class:"btn btn-warning mt-3" %>
    </div>
  <% end %>

</div>

app/views/hsups/edit.html.erb
<%= render 'form', hsup: @hsup %>

app/views/hsups/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <% if notice  %>
        <div class="alert alert-success animated slideInDown mt-3" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <div class="card mt-3">

        <table class="table">
          <thead>
            <tr class="card-header">
              <th>Qte</th>
              <th>Date</th>
              <th>Prestation</th>
              <th colspan="2"></th>
            </tr>
          </thead>

          <tbody>
            <% @hsups.each do |hsup| %>
              <tr>
                <td><%= hsup.qte %></td>
                <td><%= l(hsup.date, format: '%d/%m/%y') %></td>
                <td>
                  <a href="<%= edit_prestation_path(hsup.prestation.id) %>">
                    <%= l(hsup.prestation.debut, format: '%d/%m/%y') %> -
                    <%= l(hsup.prestation.fin, format: '%d/%m/%y') %> -
                    <%= hsup.prestation.employeur.nom %>,
                    <%= hsup.prestation.employeur.ville %>
                  </a>
                </td>
                <td><%= link_to 'Modifier', edit_hsup_path(hsup) %></td>
                <td><%= link_to 'Détruire', hsup, method: :delete, data: { confirm: 'Are you sure?' }, class:'text-danger' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

app/views/hsups/new.html.erb
<%= render 'form', hsup: @hsup %>