config/routes.rb
Rails.application.routes.draw do

  resources :hsups
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :jourferies, :intemperies, :prestations, :machines, :clients, :employeurs
  resources :factures, :facture_lignes

  root 'prestations#calendrier'

  get '/calendrier', to: 'prestations#calendrier'
  get '/factures', to: 'prestations#facture'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  has_many :prestations
end

app/models/facture.rb
class Facture < ApplicationRecord
  belongs_to :employeur
  has_many :facture_lignes, dependent: :destroy
  has_many :prestations, through: :facture_lignes

  validates_presence_of :numero, :debut, :fin
  accepts_nested_attributes_for :facture_lignes

  def total
    self.remise = 0 unless self.remise
    total = 0
    self.prestations.each do |p|
      p.hsups.each do |hs|
        total = hs.qte * 35 + total
      end
    end
    total = total + facture_lignes.sum(:montant) - self.remise
  end

end

app/models/facture_ligne.rb
class FactureLigne < ApplicationRecord
  belongs_to :prestation
  belongs_to :facture

  # validates_presence_of :debut, :fin
end

app/models/hsup.rb
class Hsup < ApplicationRecord
  belongs_to :prestation
end

app/models/intemperie.rb
class Intemperie < ApplicationRecord
  def start_time
    self.date.to_datetime
  end
  def end_time
    self.date.to_datetime
  end
end

app/models/jourferie.rb
class Jourferie < ApplicationRecord
  def start_time
    self.date.to_datetime
  end
  def end_time
    self.date.to_datetime
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
end

app/models/prestation.rb
class Prestation < ApplicationRecord
  belongs_to :employeur
  belongs_to :client
  belongs_to :machine
  has_many :hsups
  has_many :facture_lignes
  has_many :factures, through: :facture_lignes

  def start_time
    self.debut.to_datetime
  end
  def end_time
    self.fin.to_datetime
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def edit
  end

  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to clients_path, notice: 'Client créé.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to clients_path, notice: 'Client mis à jour' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:nom, :siret, :adresse, :cp, :ville)
    end
end

app/controllers/factures_controller.rb
class FacturesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_facture, only: [:show, :edit, :update, :destroy, :show]

  def index
    @factures = Facture.all.order(debut: 'desc')
  end

  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "MR-Facture#{@facture.id}",   # Excluding ".pdf" extension.
        template: "factures/show.html.erb",
        layout: 'pdf.html'#,
        #viewport_size: '1280x1024'
      end
    end
  end

  def new
    @facture = Facture.new
    @prestations = Prestation.last(2)
    @facture.prestations.build
    @facture.facture_lignes.build
  end

  def edit
    @prestations = @facture.employeur.prestations.where.not(id: @facture.facture_lignes.pluck(:prestation_id))
  end

  def create
    @facture = Facture.new(facture_params)
    respond_to do |format|
      if @facture.save
        format.html do
          redirect_to edit_facture_path(@facture)
        end
      end
    end
  end

  def update
    respond_to do |format|
      if @facture.update(facture_params)
        if @facture.save
          format.html { redirect_back fallback_location: "/factures/#{@facture.id}/edit", notice: 'Prestation ajoutée à la facture.'}
        end
      end
    end
  end

  def destroy
    @facture.destroy
    respond_to do |format|
      format.html { redirect_to factures_path, notice: 'Facture supprimée.'}
    end
  end

private

  def set_facture
    @facture = Facture.find(params[:id])
  end

  def facture_params
    params.require(:facture).permit(:employeur_id, :numero, :debut, :fin, :remise, prestation_ids: [], facture_lignes_attributes: [:id, :debut, :fin, :qte, :km, :hsup, :montant])
  end

end

app/controllers/hsups_controller.rb
class HsupsController < ApplicationController
  before_action :set_hsup, only: [:show, :edit, :update, :destroy]
  before_action :get_today_prestations, :get_all_prestations, only: [:new, :edit]

  def index
    @hsups = Hsup.all
  end

  def show
  end

  def new
    @hsup = Hsup.new
  end

  def edit
  end

  def create
    @hsup = Hsup.new(hsup_params)

    respond_to do |format|
      if @hsup.save
        format.html { redirect_to hsups_url, notice: 'Hsup créée.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @hsup.update(hsup_params)
        format.html { redirect_to hsups_url, notice: 'Hsup mise à jour.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @hsup.destroy
    respond_to do |format|
      format.html { redirect_to hsups_url, notice: 'Hsup détruite.' }
    end
  end

  private
    def set_hsup
      @hsup = Hsup.find(params[:id])
    end

    def hsup_params
      params.require(:hsup).permit(:qte, :date, :prestation_id)
    end

    def get_today_prestations
      @today_prestations = Prestation.where('debut <= ? AND fin >= ?', Date.today, Date.today)
    end

    def get_all_prestations
      @all_prestations = Prestation.all.order(fin: :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/helpers/hsups_helper.rb
module HsupsHelper
end

app/helpers/intemperies_helper.rb
module IntemperiesHelper
end

app/helpers/jourferies_helper.rb
module JourferiesHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/prestations_helper.rb
module PrestationsHelper
end

app/views/factures/_form.html.erb
<%= simple_form_for(@facture) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col">
        <%= f.association :employeur, label_method: :nom, label: fa_icon('user')+' Employeur'  %>
      </div>
      <div class="col">
        <%= f.input :numero, label: fa_icon('barcode')+' Numéro de facture'  %>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <%= f.input :debut, as: :string, input_html: {type: :date}, label: fa_icon('calendar')+' Début'  %>
      </div>
      <div class="col">
        <%= f.input :fin, as: :string, input_html: {type: :date}, label: fa_icon('calendar')+' Fin'  %>
      </div>
    </div>

    <%= render 'prestations_modal' %>

    <% if @facture.prestations.count > 0 %>

      <div class="row">
        <div class="col">
          <h5>Prestations sélectionnées : </h5>
          <div class='d-none'>
            <%= f.collection_check_boxes :prestation_ids, @facture.prestations, :id, :nomchef do |input| %>
              <%= input.check_box as: :hidden%>
            <% end %>
          </div>

          <table class="table table-stripped">
            <thead class="thead-dark">
              <tr>
                <th>Nature</th>
                <th>Employeur</th>
                <th>Client</th>
                <th><%= fa_icon('calendar')%> Début</th>
                <th><%= fa_icon('calendar')%> Fin</th>
                <th><%= fa_icon('shower')%></th>
                <th><%= fa_icon('hotel')%></th>
                <th>Qte</th>
                <th>Tarif</th>
                <th><%= fa_icon('map-marker')%> Localisation</th>
                <th><%= fa_icon('road')%> Déplacement</th>
                <th>Montant</th>
                <th colspan="2">Action</th>
              </tr>
            </thead>

            <tbody>

              <% total = 0 %>
              <%= f.simple_fields_for :facture_lignes do |ffl| %>
                  <tr>
                    <td><span class="badge badge-pill badge-warning">Prestation</span></td>
                    <td><%= ffl.object.prestation.employeur.nom %></td>
                    <td><%= ffl.object.prestation.client.nom %></td>

                    <% p = @facture.prestations.find(ffl.object.prestation_id) %>

                    <% debut = p.debut %>
                    <% if debut < @facture.debut %>
                      <% debut = @facture.debut %>
                    <% end %>
                    <% until debut.workday? %>
                      <% debut = debut + 1 %>
                    <% end %>

                    <td>
                      <small>Prestation : <%= l(p.debut, format: '%d/%m/%y') %></small><br/>
                      <%= ffl.input :debut, as: :string, input_html: {type: :date}, label: false %>
                    </td>

                    <% fin = p.fin %>
                    <% if fin > @facture.fin %>
                      <% fin = @facture.fin %>
                    <% end %>
                    <% until fin.workday? %>
                      <% fin = fin - 1 %>
                    <% end %>
                    <td>
                      <small>Prestation : <%= l(p.fin, format: '%d/%m/%y') %></small><br/>
                      <%= ffl.input :fin, as: :string, input_html: {type: :date}, label: false %>
                    </td>

                    <td>
                      <% qte_intemperie = 0.0 %>
                      <% if Intemperie.where(date: p.debut..p.fin) %>
                        <% if Intemperie.where(date: p.debut..p.fin).count > 0 %>
                          <% Intemperie.where(date: p.debut..p.fin).each do |i| %>
                            <% qte_intemperie = qte_intemperie + i.qte.to_f %>
                          <% end %>
                          <span class="badge badge-pill badge-info"><%= qte_intemperie %>j</span>
                        <% end %>
                      <% end %>
                    </td>

                    <td>
                      <% if Jourferie.where(date: debut..fin) %>
                        <% if Jourferie.where(date: debut..fin).count > 0 %>
                          <% j = Jourferie.where(date: debut..fin).count %>
                          <span class="badge badge-pill badge-danger"><%= j %>j</span>
                        <% end %>
                      <% end %>
                    </td>
                    <% if fin > debut.end_of_month %>
                      <% qte = debut.business_dates_until(fin).count %>
                    <% else %>
                      <% qte = debut.business_dates_until(fin).count + 1 %>
                    <% end %>
                    <% j = Jourferie.where(date: debut..fin).count %>
                    <% qte = qte - qte_intemperie - j %>
                    <td><%= ffl.input :qte, label: false, input_html: { value: qte }  %></td>

                    <td><span class="badge badge-pill badge-light-blue"><%= p.tarif %> €/j</span></td>
                    <td><%= p.adresse %>, <strong><%= p.ville %></strong></td>

                    <% if p.km %>
                      <% km = p.km * 0.8 * qte %>
                    <% else %>
                      <% km = 0.0 %>
                    <% end %>

                    <td><small><%= p.km.to_i  %>Km x 0.8€ x <%= qte %>j</small>
                    <%= ffl.input :km, input_html: { value: km.round(2) }, label: false %></td>

                    <% stotal = p.tarif * qte + km %>
                    <td><%= ffl.input :montant, input_html: { value: stotal }, label: false %></td>

                    <td>
                      <!-- <%= link_to 'Voir la prestation', edit_prestation_path(p), class: 'text-primary' %> -->
                      <%= ffl.button :submit, 'Modifier', class: 'btn btn-info' %>
                      <%= link_to fa_icon('close'), p.facture_lignes.first, method: :delete, data: { confirm: 'Are you sure?' }, class:'text-danger' %>
                    </td>
                  </tr>

                  <% p.hsups.each do |hs| %>
                    <tr class="table-sm">
                      <td><span class="badge badge-pill badge-orange">H sup'</span></td>
                      <td></td>
                      <td></td>
                      <td><%= l(hs.date, format: '%d/%m/%y') %></td>
                      <td><%= l(hs.date, format: '%d/%m/%y') %></td>
                      <td></td>
                      <td></td>
                      <td><%= hs.qte %>h</td>
                      <td><span class="badge badge-pill badge-pink">35€/h</span></td>
                      <td></td>
                      <td></td>
                      <td><%= hs.qte * 35 %> €</td>
                      <% total = total + hs.qte * 35 %>
                      <td></td>
                      <td></td>
                    </tr>
                  <% end %>

                    <% if @facture.remise %>
                      <% remise = @facture.remise %>
                    <% else %>
                      <% remise = 0.0 %>
                    <% end %>
                    <% total = total + stotal - remise %>
              <% end %>

              <tr class="bg-info text-light">
                <td><strong>Remise</strong></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><%= f.input :remise, label: false %></td>
                <td></td>
              </tr>

              <tr class="table-secondary">
                <th>Total TTC</th>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <th><%= (total).round(2) %> €</th>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-warning' %>
  </div>
</div>
<% end %>

app/views/factures/_prestations_modal.html.erb
<%= simple_form_for(@facture) do |f| %>

  <div class="row">
    <div class="col">
      <button type="button" class="btn btn-warning mb-3" data-toggle="modal" data-target=".bd-example-modal-xl"><%= fa_icon('wrench') %> Ajouter des prestations à la facture</button>
      <div class="modal fade bd-example-modal-xl" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-xl">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Sélectionner les prestations à ajouter à la facture : </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">

              <table class="table table-sm table-borderless">
                <thead>
                  <tr>
                    <th></th>
                    <th>Employeur</th>
                    <th>Client</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th>Machine</th>
                    <th>Localisation</th>
                  </tr>
                </thead>

                <tbody>
                  <%= f.collection_check_boxes :prestation_ids, @prestations, :id, :nomchef do |input| %>
                    <tr>
                      <td>
                        <label>
                          <%= input.check_box %>
                        </label>
                      </td>
                      <td><span class="badge badge-pill badge-<%= input.object.employeur.color %>"><%= input.object.employeur.nom %></span></td>
                      <td><%= input.object.client.nom %></td>
                      <td><%= l(input.object.debut, format: '%d/%m/%y') %></td>
                      <td><%= l(input.object.fin, format: '%d/%m/%y') %></td>
                      <td><%= input.object.machine.marque %> <%= input.object.machine.modele %></td>
                      <td><%= input.object.adresse %> <%= input.object.ville %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-warning"><%= fa_icon('plus') %> Ajouter les prestations</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/factures/edit.html.erb
<%= render 'form', facture: @facture %>

<%= link_to fa_icon('eye')+' Visualiser la facture', facture_path(@facture, :format => :pdf), class: 'mt-3 btn btn-success', :target => "_blank" %>

app/views/factures/index.html.erb
<% if notice  %>
  <div class="alert alert-success animated slideInDown mt-3" role="alert">
    <%= notice %>
  </div>
<% end %>
<table class="table table-sm table-striped table-borderless">
  <thead>
    <tr>
      <th><%= fa_icon('barcode') %> Identifiant</th>
      <th><%= fa_icon('user') %> Employeur</th>
      <th><%= fa_icon('hourglass-start') %> Début</th>
      <th><%= fa_icon('hourglass-end') %> Fin</th>
      <th><%= fa_icon('wrench') %> NB prestations</th>
      <th><%= fa_icon('money') %> Remise</th>
      <th><%= fa_icon('money') %> Total</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @factures.each do |f| %>
      <tr>
        <td><%= f.numero %></td>
        <td><span class="badge badge-pill badge-<%= f.employeur.color %>"><%= f.employeur.nom %></span></td>
        <td><%=  l(f.debut, format: '%d/%m/%y') %></td>
        <td><%=  l(f.fin, format: '%d/%m/%y') %></td>
        <td><span class="badge badge-pill badge-warning"><%=  f.prestations.count %></span></td>
        <td><%= f.remise %> €</td>
        <td><%= f.total.round(2) %> €</td>

        <td><%= link_to 'Visualiser', facture_path(f, :format => :pdf), :target => "_blank" %></td>
        <td><%= link_to 'Modifier', edit_facture_path(f) %></td>
        <td><%= link_to 'Détruire', f, method: :delete, data: { confirm: 'Are you sure?' }, class:'text-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/factures/new.html.erb
<%= render 'form', facture: @facture %>

app/views/factures/show.html.erb
<div class="container">

  <div class="mt-3">
    <div class="float-left">
      <%= wicked_pdf_image_tag 'mrlogo300.png', width: '200px' %>
    </div>
    <div class="float-right">
      <h6>Identifiant facture : <%= @facture.numero %></h6>
      <p>Le <%=l(@facture.updated_at, format: '%d/%m/%Y')%></p>
    </div>
  </div>

  <div style="clear:both"></div>

  <div class="mt-3">
    <div class="float-left card border-amber">
      <div class="card-body">
        <strong>Rasic Mattew</strong><br/>
        55 route de Madirac<br/>
        33880, Saint-Caprais-de-Bordeaux<br/>
        06 60 90 20 28<br/>
        SIRET : 80184268300022<br/>
      </div>
    </div>
    <div class="float-right card border-amber">
      <div class="card-body">
        <strong><%= @facture.employeur.nom %></strong><br/>
        <%= @facture.employeur.adresse %><br/>
        <%= @facture.employeur.cp %>, <%= @facture.employeur.ville %><br/>
        <%= @facture.employeur.tel %><br/>
        SIRET : <%= @facture.employeur.siret %>
      </div>
    </div>
  </div>

  <div style="clear:both"></div>

  <br/>
  <h4 class="bg-light-blue text-white p-2 mt-3 mb-3">Objet : Facture des prestations du mois de <%= l(@facture.debut, format: '%B %Y') %></h4>
  <br/>
  <div class="row mt-3 mb-3">
    <div class="col">
      <table class="table table-sm table-striped" style="font-size:0.8em;">
        <thead>
          <tr>
            <th>Nature</th>
            <th>Client</th>
            <th>Début</th>
            <th>Fin</th>
            <th>Localisation</th>
            <th>Chef</th>
            <th>Pelle</th>
            <th>Tarif</th>
            <th>Déplace.</th>
            <th>Qte</th>
            <th>Montant</th>
          </tr>
        </thead>
        <tbody>
          <% @facture.facture_lignes.each do |fl| %>
            <tr>
              <td><span class="badge badge-light-blue">Prestation</span></td>
              <td><%= fl.prestation.client.nom %></td>
              <td><%= l(fl.debut, format: '%d/%m/%y') %></td>
              <td><%= l(fl.fin, format: '%d/%m/%y') %></td>
              <td><%= fl.prestation.adresse %>, <strong><%= fl.prestation.ville %></strong></td>
              <td><%= fl.prestation.nomchef %></td>
              <td><%= fl.prestation.machine.marque %> <%= fl.prestation.machine.modele %>, <%= fl.prestation.machine.poids %>t</td>
              <td><span class="badge badge-pill badge-light-blue"><%= fl.prestation.tarif %>€/j</span></td>
              <td><span class="badge badge-pill badge-vlight-blue">+<%= fl.km/fl.qte  %>€/j</span></td>
              <td><span class="badge badge-pill badge-amber"><%= fl.qte %>j</span></td>
              <td><strong><%= fl.montant %>€</strong></td>
            </tr>
            <% fl.prestation.hsups.each do |hs| %>
              <tr>
                <td><span class="badge badge-vlight-blue">H supp.</span></td>
                <td><%= fl.prestation.client.nom %></td>
                <td><%= l(hs.date, format: "%d/%m/%y") %></td>
                <td><%= l(hs.date, format: "%d/%m/%y") %></td>
                <td><%= fl.prestation.adresse %>, <strong><%= fl.prestation.ville %></strong></td>
                <td><%= fl.prestation.nomchef %></td>
                <td><%= fl.prestation.machine.marque %> <%= fl.prestation.machine.modele %>, <%= fl.prestation.machine.poids %>t</td>
                <td><span class="badge badge-pill badge-light-blue">35 €/h</span></td>
                <td><%= %></td>
                <td><span class="badge badge-pill badge-amber"><%= hs.qte %>h</span></td>
                <td><strong><%= 35 * hs.qte %> €</strong></td>
              </tr>
            <% end %>
          <% end %>
            <tr class="table-light">
              <th>Remise</th>
              <td colspan="9"></td>
              <th><strong><%= @facture.remise %>€</strong></th>
            </tr>
            <tr class="table-light">
              <th>Total HT</th>
              <td colspan="9"></td>
              <th><strong><%= @facture.total %>€</strong></th>
            </tr>
            <tr class="table-secondary">
              <th>Total TTC</th>
              <td colspan="9"></td>
              <th><strong><%= @facture.total %>€</strong></th>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
<br/>
  <div class="row mt-3">
    <div class="col">
      <div class="alert alert-light-blue text-center">
        Merci pour votre confiance.
      </div>
    </div>
  </div>

</div>