config/routes.rb
Rails.application.routes.draw do

  resources :hsups
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :jourferies, :intemperies, :prestations, :machines, :clients, :employeurs
  resources :factures, :facture_lignes

  root 'prestations#calendrier'

  get '/calendrier', to: 'prestations#calendrier'
  get '/factures', to: 'prestations#facture'
end

app/models/employeur.rb
class Employeur < ApplicationRecord
  has_many :prestations
end

app/controllers/employeurs_controller.rb
class EmployeursController < ApplicationController
  before_action :set_employeur, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @employeurs = Employeur.all
  end

  def show
  end

  def new
    @employeur = Employeur.new
  end

  def edit
  end

  def create
    @employeur = Employeur.new(employeur_params)

    respond_to do |format|
      if @employeur.save
        format.html { redirect_to employeurs_path, notice: 'Employeur was successfully created.' }
        format.json { render :show, status: :created, location: @employeur }
      else
        format.html { render :new }
        format.json { render json: @employeur.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employeur.update(employeur_params)
        format.html { redirect_to employeurs_path, notice: 'Employeur was successfully updated.' }
        format.json { render :show, status: :ok, location: @employeur }
      else
        format.html { render :edit }
        format.json { render json: @employeur.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employeur.destroy
    respond_to do |format|
      format.html { redirect_to employeurs_url, notice: 'Employeur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employeur
      @employeur = Employeur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employeur_params
      params.require(:employeur).permit(:nom, :siret, :adresse, :cp, :ville, :tel, :email, :email2, :color)
    end
end

app/helpers/employeurs_helper.rb
module EmployeursHelper
end

app/views/employeurs/_form.html.erb
<div class="container">
  <%= simple_form_for(@employeur) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :nom %>
      <%= f.input :siret %>
      <%= f.input :adresse %>
      <%= f.input :cp %>
      <%= f.input :ville %>
      <%= f.input :tel %>
      <%= f.input :email %>
      <%= f.input :email2 %>
      <%= f.input :color %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-warning' %>
    </div>
  <% end %>
</div>

app/views/employeurs/edit.html.erb
<%= render 'form', employeur: @employeur %>

app/views/employeurs/index.html.erb
<% if notice  %>
  <div class="alert alert-success animated slideInDown" role="alert">
    <%= notice %>
  </div>
<% end %>
<table class="table table-hover table-borderless">
  <thead>
    <tr>
      <th><%= fa_icon('user') %> Nom</th>
      <th><%= fa_icon('barcode') %> Siret</th>
      <th><%= fa_icon('map-marker') %> Adresse</th>
      <th><%= fa_icon('barcode') %> Code postal</th>
      <th><%= fa_icon('institution') %> Ville</th>
      <th><%= fa_icon('phone') %> Tel</th>
      <th><%= fa_icon('envelope') %> Email</th>
      <th><%= fa_icon('envelope') %> Email2</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @employeurs.each do |employeur| %>
      <tr>
        <td><span class="badge badge-pill badge-<%= employeur.color %>"><%= employeur.nom %></span></td>
        <td><%= employeur.siret %></td>
        <td><%= employeur.adresse %></td>
        <td><%= employeur.cp %></td>
        <td><%= employeur.ville %></td>
        <td><%= employeur.tel %></td>
        <td><%= employeur.email %></td>
        <td><%= employeur.email2 %></td>
        <td><%= link_to 'Modifier', edit_employeur_path(employeur) %></td>
        <td><%= link_to 'Détruire', employeur, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employeurs/new.html.erb
<%= render 'form', employeur: @employeur %>

app/views/employeurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @employeur.nom %>
</p>

<p>
  <strong>Siret:</strong>
  <%= @employeur.siret %>
</p>

<p>
  <strong>Adresse:</strong>
  <%= @employeur.adresse %>
</p>

<p>
  <strong>Cp:</strong>
  <%= @employeur.cp %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @employeur.ville %>
</p>

<p>
  <strong>Tel:</strong>
  <%= @employeur.tel %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employeur.email %>
</p>

<p>
  <strong>Email2:</strong>
  <%= @employeur.email2 %>
</p>

<%= link_to 'Edit', edit_employeur_path(@employeur) %> |
<%= link_to 'Back', employeurs_path %>